### ISSUE TITLE
Features request.

### ISSUE THREAD

**Issue by RustyRaptor** [trueleo/me.trueleo.cuteshapes#3]
This is super cool. Would be nice if it had more features though. Here are some I thought of. 

1. adjust radius of shadow (it's hard to see sometimes)
2. Change background 
3. Change position of circle 
4. Adjust size of circle. (maybe shadow should be a fixed ratio to the circle size when this happens)
5. Custom icons. (maybe have a template for people to work with so it fits)

**Comment by trueleo** [comment]
Sorry for late reply. I actually wanted to add several other stuff, animated objects to wallpaper and also allow users to change background of their likings. But problem is that many of these can make plasma loadup time slower and certainly will use resources.

And having circle with logo as "plasmoid widget" makes more sense to me because people can move it around and resize it however they like. I might do that but I can't promise much as of now.

**Comment by trueleo** [comment]
Just to close this issue. I pushed some features onto master branch so you can check that out. I won't be able to develop this beyond this point. Something much better @ https://github.com/zzag/dynamic-wallpaper.
